In [16]:
import pandas as pd

In [17]:
df_mod = pd.read_csv('./data/modified.csv')
df_pur = pd.read_csv('./data/purple.csv')

C:\Users\castr\AppData\Local\Temp\ipykernel_23760\3272812649.py:1: DtypeWarning: Columns (16) have mixed types. Specify dtype option on import or set low_memory=False.
  df_mod = pd.read_csv('./data/modified.csv')
C:\Users\castr\AppData\Local\Temp\ipykernel_23760\3272812649.py:2: DtypeWarning: Columns (3,37,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,83,84,85,87,88,89,90,92,93,94,96,97,98,99,100,101,103,104,105,106,107,108,109,110,111,112,113,114,115,116,117,118,119,120,121,122,125,126,127,128,129,132,134,135,136,137,138,139,140,141,142,143,145,147,148,149,150,151,152,153,154,155,156,157,158,159,160,161,164,165,167,168,169,170,171,172,173,174,176,177,178,179,180,181,182,183,185,186,187,188,189,190,192,193,194) have mixed types. Specify dtype option on import or set low_memory=False.
  df_pur = pd.read_csv('./data/purple.csv')

In [18]:
df_mod.head()

,Unnamed: 0,event_id,process_name,hostname,hostname_role,event_type,hour_of_day,day_of_week,user_context,is_admin_process,...,protocol,is_outbound,source_address,dest_address,process_path,parent_process_path,command_line,file_path,file_name,file_extension
0,0,5156,\device\harddiskvolume2\windows\system32\lsass...,MORDORDC.theshire.local,Server,AUDIT_SUCCESS,8,Thursday,NaN,0,...,6,0,::1,::1,NaN,NaN,NaN,NaN,NaN,NaN
1,1,5156,\device\harddiskvolume2\windows\system32\ismse...,MORDORDC.theshire.local,Server,AUDIT_SUCCESS,8,Thursday,NaN,0,...,6,0,::1,::1,NaN,NaN,NaN,NaN,NaN,NaN
2,2,5156,\device\harddiskvolume2\windows\system32\lsass...,MORDORDC.theshire.local,Server,AUDIT_SUCCESS,8,Thursday,NaN,0,...,6,0,::1,::1,NaN,NaN,NaN,NaN,NaN,NaN
3,3,5156,\device\harddiskvolume2\windows\system32\lsass...,MORDORDC.theshire.local,Server,AUDIT_SUCCESS,8,Thursday,NaN,0,...,6,0,::1,::1,NaN,NaN,NaN,NaN,NaN,NaN
4,4,5156,\device\harddiskvolume2\windows\system32\ismse...,MORDORDC.theshire.local,Server,AUDIT_SUCCESS,8,Thursday,NaN,0,...,6,0,::1,::1,NaN,NaN,NaN,NaN,NaN,NaN

In [19]:
df_pur.head()

,Unnamed: 0,@timestamp,DestPort,ProcessId,OpcodeValue,port,SourceAddress,RemoteMachineID,Severity,SourcePort,...,ClientCreationTime,KeyType,ReturnCode,KeyFilePath,KeyName,ProviderName,MiniportNameLen,MiniportName,param3,param4
0,0,2020-10-22T08:29:48.785Z,389.0,696,0.0,58121,::1,S-1-0-0,INFO,49678.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1,2020-10-22T08:29:48.785Z,389.0,3632,0.0,58121,::1,S-1-0-0,INFO,49678.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2,2020-10-22T08:29:48.785Z,389.0,696,0.0,58121,::1,S-1-0-0,INFO,49678.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,3,2020-10-22T08:29:48.785Z,389.0,696,0.0,58121,::1,S-1-0-0,INFO,49679.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,4,2020-10-22T08:29:48.786Z,389.0,3632,0.0,58121,::1,S-1-0-0,INFO,49679.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [23]:
new = pd.DataFrame()
new['event_id'] = df_mod['event_id']
new.head()

   event_id
0      5156
1      5156
2      5156
3      5156
4      5156

In [24]:
new['process_name'] = df_mod['process_name']

In [31]:
new.head()

,event_id,process_name,hostname,hostname_role,event_type
0,5156,\device\harddiskvolume2\windows\system32\lsass...,MORDORDC.theshire.local,Server,AUDIT_SUCCESS
1,5156,\device\harddiskvolume2\windows\system32\ismse...,MORDORDC.theshire.local,Server,AUDIT_SUCCESS
2,5156,\device\harddiskvolume2\windows\system32\lsass...,MORDORDC.theshire.local,Server,AUDIT_SUCCESS
3,5156,\device\harddiskvolume2\windows\system32\lsass...,MORDORDC.theshire.local,Server,AUDIT_SUCCESS
4,5156,\device\harddiskvolume2\windows\system32\ismse...,MORDORDC.theshire.local,Server,AUDIT_SUCCESS

In [28]:
new['hostname'] = df_mod['hostname']
new['hostname_role'] = df_mod['hostname_role']

In [30]:
new['event_type'] = df_mod['event_type']